# -*- coding: utf-8 -*-
"""
Created on Mon Dec  9 17:55:50 2019

@author: Rosa
"""


Rosalind_14 = "AAGCTTAGATTGCTGTTTAAGATTCGGCTCGAAGCCTACAGACTGGGATCTAGGACACCTTCGTCATCCGCTGCCGCTCGCGATGACCAATTAACTCTCTAACCCACTGACAGGTTGCTCACCCCCAGTTATTGCGGGGAAGGGGGAGTATACTCGCGTGTTTAACTACATTGTCGATGGTCATATACGTCCTCAACGCGTAATAAAAGTCGTCGTGCACCAAGGGATGAGTCCTATATATCTGCATCAAGCTAATCCCTACGGTAGCGTACGGCGTTAGCAGAATGGTGCTAGGGCTACATTGATCGCATGTACTTGCCGGTCGGCATTCGGCCTGTAATTGGCCCCTCAGGCTAACTGGGCTCCGAAGATAGCCACCAGGGTCAGAGTCCGACAGTGCCCCATAGGTTGTCCAACTGTGGCATTCGTCCATGTACAATGTTTTGCGTCCTATTTTTGAAGGTTGCCTGTGATCAGGAGATTCGAAAGCTTAAGATTGCTTGAGACTTTATTGGGATCCGCAATTTTCATCGTTTTTACGAGTAGGGCTGTAATGCACCAGTTTAGAGTCACCACCGGTGCGGTGTACCATAGAGGCTCTATTAATTTTTCTCCGTAATATGCATTAATGGGCCACAATGTATGGACCTCGGCGAGCTCAGGACAGGCCTTCTCTTTCAAATCATGTTAGAAAGACTATCATACCGTTTCCTAAAAATGAGTTCTTCGGCATTCTCTCCATCAAAACGTTCGCCCTAACTTTGTCACGAGTGGTGCAGGGAAGTTCGCAACGGTAGGTGGACTGGTGATC"
Rosalind_18 = "CATACCAAGCCCAAGAATCGTACGGAGGCGCAATACTAGGATCCGTCTAAAC"
#l = 0
def eee( Rosalind_14, Rosalind_18):
    
    res = ''
    l = 0
    #for e in Rosalind_14:
    for i in Rosalind_18:
            #if i in Rosalind_14:
        r = Rosalind_14.find(i) 
                #w =  (Rosalind_14.index(i) +1)
        res = res + str(r + 1 + l)  + " "
        l = l + r +1
        Rosalind_14 = Rosalind_14[r + 1:]
    return res
                
    
print(eee(Rosalind_14,Rosalind_18))
 #print(t)
#print(s)