# -*- coding: utf-8 -*-
"""
Created on Thu Nov 28 21:25:59 2019

@author: Rosa
"""


s1 = "GGTCGAATCGCCGTAAACTATAGCATACTGGTCGTATCGTCATGTAGGCAACATCTTGGTCTGCGCGTGCCGCTATAAAGTTTAGCCGACGATCAGCTGTTCATGACCGGCTCCACCGGTTCCCGTTTATCCTGATCCCAAGTGGCGAGTTATAGTACAAGTAGGTTCGGCGTGTGTCACAAATCTGGGACCCCCCCAGCTGGGCGAAGAATTCTATATAAAGCGTCCCTTGAATATCTAAAGGCGGGAGCGCGTATAAGACGGGTCTGGGATCTCGCGACTTGACTCCATTTAGCGGACCACTCGCATCATAGTAATCACCGTTCCAATTTCTCTAGTATCGGTCCCTGTATCGTGCGACTGCCGGGAGCTATAGTCTCAGCATGATTATGGTATGCATAATTGCACTACAGTAACCTATCTCAGTCATGTGTACAACACATTAGGTTTCTTGGAAGTATTGAGACGTATTCGACACGCGCAGGGTAAGATATCAGCGCGGTCACCGCCCCGATACCAATTGGTCTTGCCCAATTACCCCACTTTGCCGGCTTTCGGCAAGGCGGCTGGGCCCGAACGGACAGATGGTTCTGATGTCACCTTTTCTGCGGCTGCGTACCTCTAAATGGTACAAGAGGCGCTCGATTACTCTAGGATTAGGTAGCTTCGTCGCAGTGTAAGACCTCTCAGGAACTCTAGAAGGTCCTACAAAGCGCTATCGACCAACACCGTCCAGACGGGCGTAACTTTGAGGCCGGTAGTACCTATCATGAGGGATAGTGGGATCGGGACACCATACGTGCATCGGCTGCGTACGGGCTCCCCCGGGTTGGCGAGGGCCGGATTCGGTAACCAAGGTACGCTCGGTCGTTTAACACGGTACCAAGCGGCCCAATATACCCGGGCACCAGCACGGACGACA"

s2 = "GGTAGCATCGCCAGGGACTTCAGCATATTGGCCGCACCATCGTGTAAAGATCACACGGGTCTGCGCCTGCCGCTATAACACCTTGTCAATGATCCGTTGTCTATCACGGGACGCGCCAGTTCTCATTTACCTAAACCTCATATGCCGAGTTATAGTGCAGGTATAAACGAGGTGTGTCGCAAACCTGGGACCCCCCCGGCCGGGCGTAAAATATTACATGACGGGTTCTTTAAGCTTCCACAGGCGGAAGTGCGGGTAAGATGCGTTTAGAATCTCACAACCTAGCTCCATTCAGAGGACTACTCGCTCCCTAGTGCTCACCGCTATAATCACTCTAATATTGCTCCCTTTATCGTACGGTTGACGGAAACAATTATCTCAGCGAGATTGTGGTATGCATAATTGCACTACAGCAACTCTTGTTAGTACTGTTTACAAAACATGTGGGTTCTGTATCGTATTGAGGAGCATTCCAGACGTGTAAGTCATGACATCTATGCAGTTGCTACCAAAATATCAACTGGTCTCGTCCAACTATCCCAGCTTCGCGGCCTTTGGCGGGGCAATTGGGCCCGCATAGACAGGTAATCCTGGCGTCACATTTCTTGCAATTATGTATGTCTTAATGGTACCGGTGGTGCCTGATCACTCTAGGATTAGGTAACTTCGCTGCGGTTCAAGACCTCATAGGAATTTTAGGGTGTTCCGTGAAGCGCGATCGCCCCACATCGTCCAGACAGGTCTGATTCCGGGGCTAGTAGCACTTATCGTAGGAGACAGCGCGATTGGAACCTCGCACGTGCACCAGCTAAGCAGGGGCTCCCCCAGGTTAGCAAGGACTGGGTTAACTGACCAGGGTATGTTCGATCGTTTAGCTCGGCATCAAGCGGTTTAATGTACCCGGGCGGCAGCACAGATGGCG"
def tran(s1,s2):
    transition = 0
    transvetion = 0
    for ch1, ch2 in zip(s1, s2):
        if ch1 == ch2:
            continue
        elif ch1 != ch2:
            if ch1 == 'A' and ch2 == 'G':
                 transition += 1
            elif ch1 == 'G' and ch2 == 'A':
                transition += 1
            elif ch1 == 'T' and ch2 == 'C':
                transition += 1
            elif ch1 == 'C' and ch2 == 'T':
                transition += 1
            elif ch1 == 'A' and (ch2 == 'T' or ch2 == 'C'):
                transvetion += 1
            elif ch1 == 'T' and (ch2 == 'A' or ch2 == 'G'):
                transvetion += 1
            elif ch1 == 'G' and (ch2 == 'C' or ch2 == 'T'):
                transvetion += 1
            elif ch1 == 'C' and (ch2 == 'G' or ch2 == 'A'):
                transvetion += 1
    
    return (round((transition/transvetion),11))
    
    
print(tran(s1,s2))
